WatchStore/Controllers/ModuleController.cs
using WatchStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WatchStore.Controllers
{
    public class ModuleController : Controller
    {
        private WatchStoreDbContext db = new WatchStoreDbContext();
        // GET: Module
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Header()
        {
            return View("_Header");
        }
        public ActionResult CategorySearch()
        {
            var list = db.Categorys
               .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_CategorySearch",list);
        }
        public ActionResult Cart()
        {
            return View("_Cart");
        }
        public ActionResult Navbar()
        {
            return View("_Navbar");
        }
        public ActionResult ProductView()
        {
            return View("_ProductView");
        }
        public ActionResult LatestNew()
        {
            var list = db.Posts
               .Where(m => m.Status == 1 && m.Type == "post")
               .Take(3)
               .OrderByDescending(m => m.Created_At )
               .ToList();
            return View("_LatestNew", list);
        }

        public ActionResult LatestNewListing()
        {
            var list = db.Posts
               .Where(m => m.Status == 1 && m.Type == "post")
               .Take(8)
               .OrderByDescending(m => m.Created_At)
               .ToList();
            return View("_LatestNewListing", list);
        }

        public ActionResult Brand()
        {
            return View("_Brand");
        }
        public ActionResult CompanyFacality()
        {
            return View("_CompanyFacality");
        }
        public ActionResult Footer()
        {
            return View("_Footer");
        }
        public ActionResult Copyright()
        {
            return View("_Copyright");
        }
        public ActionResult LinkHeader()
        {
            return View("_LinkHeader");
        }
        public ActionResult LinkFooter()
        {
            return View("_LinkFooter");
        }
        public ActionResult Category()
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_Category", list);
        }

        public ActionResult CategoryChild(int id)
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == id);
            return View("_CategoryChild", list);
        }

        public ActionResult CategoryFooter()
        {
            var list = db.Categorys
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("_CategoryFooter", list);
        }
        public ActionResult ProductNew()
        {
            var list = db.Products
               .Where(m => m.Status == 1 && m.Discount != 0)
               .Take(8)
               .ToList();
            return View("_ProductNew", list);
        }

        public ActionResult Sale()
        {
            var list = db.Products
               .Where(m => m.Status == 1)
               .Take(8)
               .OrderByDescending(m=>m.Created_at)
               .ToList();
            return View("_Sale", list);
        }


        public ActionResult Sell()
        {
            var list = (from p in db.Products
                        let totalQuantity = (from op in db.Orderdetails
                                             join o in db.Orders on op.OrderId equals o.Id
                                             where op.ProductId == p.ID 
                                             select op.Quantity).Sum()
                        where totalQuantity > 0
                        orderby totalQuantity descending
                        select p).Take(8);
            return View("_Sell", list);
        }

        public ActionResult Feature()
        {
          
            return View("_Feature");
        }

        public ActionResult SlideShow()
        {
            return View("_SlideShow",db.Sliders.Where(m=>m.Status!=0).ToList());
        }
        public ActionResult ListPage()
        {
            var list = db.Posts
              .Where(m => m.Status == 1 && m.Type=="page")
              .OrderByDescending(m => m.Created_At)
              .ToList();
            return View("_ListPage",list);
        }
        public ActionResult MainMenu()
        {
            var list = db.Menus
              .Where(m => m.Status == 1 && m.Position=="mainmenu")
              .ToList();
            return View("_MainMenu", list);
        }

        public ActionResult MainMenuWithCategory()
        {
            var listCat = db.Categorys
              .Where(m => m.Status == 1 && m.ParentId == 0);

            int[] arrayID = new int[] { 8,19 }; // array parent ID

            ViewBag.ListCatID = arrayID;
            return View("_MainMenuWithCategory", listCat);
        }

        public ActionResult MainMenuWithSubCategory(int id)
        {
            var listCat = db.Categorys
              .Where(m => m.Status == 1 && m.ParentId == id);

            return View("_MainMenuWithSubCategory", listCat);
        }
        public ActionResult MainMenuMobile()
        {
            var list = db.Menus
              .Where(m => m.Status == 1 && m.Type == "custom")
              .ToList();
            return View("_MainMenuMobile", list);
        }
        public ActionResult ListCate()
        {
            return View("_ListCate", db.Categorys.Where(m => m.Status != 0 && m.ParentId==0).ToList());
        }
        public ActionResult Posts()
        {
            var list = db.Topics 
                .Where(m => m.Status == 1 && m.ParentId == 0);
            return View("Posts", list);
        }
        public ActionResult PostHome(int topid)
        {
            List<int> listtopid = new List<int>();
            listtopid.Add(topid);

            var list2 = db.Topics
                .Where(m => m.ParentId == topid).Select(m => m.Id)
                .ToList();
            foreach (var id2 in list2)
            {
                listtopid.Add(id2);
                var list3 = db.Topics
                    .Where(m => m.ParentId == id2)
                    .Select(m => m.Id).ToList();
                foreach (var id3 in list3)
                {
                    listtopid.Add(id3);
                }
            }

            var list = db.Posts
                .Where(m => m.Status == 1 && listtopid
                .Contains(m.Topid))
                .Take(12)
                .OrderByDescending(m => m.Created_At);

            return View("PostHome", list);
        }
        public ActionResult ListTopic()
        {
            return View("ListTopic", db.Topics.Where(m => m.Status != 0 && m.ParentId == 0).ToList());
        }
        public ActionResult PListPage()
        {
            var list = db.Posts
                .Where(m => m.Status == 1 && m.Type == "page");
            return View("PListPage", list);
        }
        public ActionResult RecentlyViewedProducts()
        {
            var list = Session["RecentlyViewedProducts"];
            
            return View("_RecentlyViewedProducts", list); ;
            
        }
    }
}

WatchStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

WatchStore/Views/Shared/_LayoutSite.cshtml
<!doctype html>
<html lang="en">
<head>
    @*@Html.Action("LinkHeader","Module")*@
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/Public/user/img/favicon.png">
    <link rel="stylesheet" href="~/Public/user/css/animate.css">
    <link rel="stylesheet" href="~/Public/user/css/jquery.fancybox.css">
    <link rel="stylesheet" href="~/Public/user/css/jquery.bxslider.css">
    <link rel="stylesheet" href="~/Public/user/css/meanmenu.min.css">
    <link rel="stylesheet" href="~/Public/user/css/jquery-ui-slider.css">
    <link rel="stylesheet" href="~/Public/user/css/nivo-slider.css">
    <link rel="stylesheet" href="~/Public/user/css/owl.carousel.css">
    <link rel="stylesheet" href="~/Public/user/css/owl.theme.css">
    <link rel="stylesheet" href="~/Public/user/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Public/user/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Public/user/css/normalize.css">
    <link rel="stylesheet" href="~/Public/user/css/main.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/Public/user/css/style.css">
    <link rel="stylesheet" href="~/Public/user/css/responsive.css">
    <link rel="stylesheet" href="~/Public/user/css/ie.css">
    <script src="~/Public/user/js/vendor/modernizr-2.6.2.min.js"></script>
    <link href="~/Public/user/css/alert.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="~/Public/js/sweetalert2@9.js"></script>
    <script src="~/Public/user/js/vendor/jquery-1.11.3.min.js"></script>

</head>
<body class="index-2">
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v10.0&appId=206736594217518&autoLogAppEvents=1" nonce="fl855pxE"></script>
    @Html.Action("Header", "Module")
    @Html.Action("Cart", "Module")
    @RenderBody()
    @*@Html.Action("Brand", "Module")*@
    @Html.Action("CompanyFacality", "Module")
    @Html.Action("Footer", "Module")
    @Html.Action("Copyright", "Module")

    @*@Html.Action("LinkFooter", "Module")*@
    <script src="~/Public/user/js/jquery.fancybox.js"></script>
    <script src="~/Public/user/js/jquery.bxslider.min.js"></script>
    <script src="~/Public/user/js/jquery.meanmenu.js"></script>
    <script src="~/Public/user/js/owl.carousel.min.js"></script>
    <script src="~/Public/user/js/jquery.nivo.slider.js"></script>
    <script src="~/Public/user/js/jqueryui.js"></script>
    <script src="~/Public/user/js/bootstrap.min.js"></script>
    <script src="~/Public/user/js/wow.js"></script>
    <script src="~/Public/js/target.min.js"></script>

    <script src="~/Public/js/popper.min.js"></script>

    <script>
        new WOW().init();
    </script>
    @*<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=601bab9dd2f8290011987836&product=sticky-share-buttons" async="async"></script>*@
    <script src="~/Public/user/js/main.js"></script>
</body>
</html>

WatchStore/Views/Shared/_Nofit.cshtml
@if (Notification.has_flash())
{
    ModelNotification Notifi = Notification.get_flash();
<input type="hidden" value="@Notifi.mgs_type" name="u_mgs_type" />
                <input type="hidden" value=" @Notifi.mgs" name="u_mgs" />}